class User {
    constructor(uid, email, password, username) {
        this.uid = uid; // represents the id generated by the firestore
        this.email = email;
        this.password = password;
        this.username = username;
    }
}

module.exports = User;